#!/bin/sh

# project path,{0} is placeholder
base_dir="{0}" 
dart format "$base_dir"
# pre_commit.dart path, {1} is placeholder
pre_commit="{1}"
errorInfo="Please fix the errors and then submit the code."
echo "\033[32;1mChecking the code before submit...\033[0m"
echo "\033[32;1mAnalyzing $base_dir...\033[0m"

info=$(dart "$pre_commit" "$base_dir")

echo "$info"

if [[ -n $info && $info != *"No issues found"* ]];then
echo "\033[31;1m$errorInfo\033[0m"
exit 1
fi
