name: candies_analyzer_plugin
description: The plugin to help create custom analyzer plugin quickly and provide some useful lints and get suggestion and auto import for extension member.
version: 3.3.1
homepage: https://github.com/fluttercandies/candies_analyzer_plugin

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  logger: ^1.1.0
  yaml: ^3.1.1
  pubspec_parse: ^1.2.1
  io: ^1.0.3
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4

executables:
  candies_analyzer_plugin: main

# dart pub global activate --source path ./
# candies_analyzer_plugin clear_cache